Update _misc.py
This part of the code raised the following error for me: AttributeError: module 'jax.numpy' has no attribute 'astype'. Did you mean: 'dtype'?. Therefore, this is my proposed solution.